/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteButton: typeof import('./src/components/parse/parsed/DeleteButton.vue')['default']
    DownloadButton: typeof import('./src/components/parse/parsed/DownloadButton.vue')['default']
    DownloadItem: typeof import('./src/components/download/DownloadItem.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    ParsedItem: typeof import('./src/components/parse/ParsedItem.vue')['default']
    ParseItem: typeof import('./src/components/parse/ParseItem.vue')['default']
    PreviewItem: typeof import('./src/components/parse/parsed/PreviewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleItem: typeof import('./src/components/TitleItem.vue')['default']
    VarAlert: typeof import('@varlet/ui')['_AlertComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarButtonGroup: typeof import('@varlet/ui')['_ButtonGroupComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarMenuOption: typeof import('@varlet/ui')['_MenuOptionComponent']
    VarMenuSelect: typeof import('@varlet/ui')['_MenuSelectComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}

// For TSX support
declare global {
  const DeleteButton: typeof import('./src/components/parse/parsed/DeleteButton.vue')['default']
  const DownloadButton: typeof import('./src/components/parse/parsed/DownloadButton.vue')['default']
  const DownloadItem: typeof import('./src/components/download/DownloadItem.vue')['default']
  const NavItem: typeof import('./src/components/NavItem.vue')['default']
  const ParsedItem: typeof import('./src/components/parse/ParsedItem.vue')['default']
  const ParseItem: typeof import('./src/components/parse/ParseItem.vue')['default']
  const PreviewItem: typeof import('./src/components/parse/parsed/PreviewItem.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TitleItem: typeof import('./src/components/TitleItem.vue')['default']
  const VarAlert: typeof import('@varlet/ui')['_AlertComponent']
  const VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
  const VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
  const VarButton: typeof import('@varlet/ui')['_ButtonComponent']
  const VarButtonGroup: typeof import('@varlet/ui')['_ButtonGroupComponent']
  const VarCard: typeof import('@varlet/ui')['_CardComponent']
  const VarCell: typeof import('@varlet/ui')['_CellComponent']
  const VarIcon: typeof import('@varlet/ui')['_IconComponent']
  const VarInput: typeof import('@varlet/ui')['_InputComponent']
  const VarMenuOption: typeof import('@varlet/ui')['_MenuOptionComponent']
  const VarMenuSelect: typeof import('@varlet/ui')['_MenuSelectComponent']
  const VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
  const VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
}