name: CI

on:
  push:
    tags: v*.*.*

permissions:
  contents: write

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install Go
        uses: actions/setup-node@v6
        with:
          node-version-file: src/frontend/package.json
          cache: npm
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        run: make install-frontend

      - name: Test units
        run: make test-frontend

  build-frontend:
    needs: test-frontend
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install dependencies
        run: make install-frontend

      - name: Build frontend
        run: make build-frontend

      - uses: actions/upload-artifact@v7
        with:
          name: build-frontend
          path: dist/frontend

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install YT-DLP
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: src/backend/go.mod
          cache-dependency-path: src/backend/go.sum

      - name: Install dependencies
        run: make install-backend
      
      - name: Test units
        run: make test-backend

  build-backend:
    needs:
      - test-backend
      - build-frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ arm64, amd64, 386 ]
        exclude:
          - os: darwin
            arch: 386
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: build-frontend
          path: dist/frontend

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: src/backend/go.mod
          cache-dependency-path: src/backend/go.sum

      - name: Install nFPM
        run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

      - name: Install dependencies
        run: make install-backend

      - name: Build backend
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make build-backend

      - name: Build packages
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make package

      - uses: actions/upload-artifact@v7
        with:
          name: build-backend_${{ matrix.os }}_${{ matrix.arch }}
          path: dist/backend

  release:
    needs: build-backend
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: dist/backend
          pattern: build-backend_*_*
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          name: DLP UI ${{ github.ref_name }}
          files: dist/backend/*